language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.3
      env: MIX_ENV=test
    - otp_release: 19.1
      elixir: 1.3.3
      env: MIX_ENV=test
sudo: false
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix test
